[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ArthurLimaS/ir-med/blob/main/example_notebook.ipynb)

# Loading CMED data

In [1]:
import etl_functions as etl

df_cmed = etl.load_cmed(path = "data/cmed/cmed_clean_03_2024.csv")

In [2]:
df_cmed

,SUBSTÂNCIA,CÓDIGO GGREM,REGISTRO,EAN 1,EAN 2,EAN 3,PRODUTO,APRESENTAÇÃO
0,21-ACETATO DE DEXAMETASONA;CLOTRIMAZOL,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,"10 MG/G + 0,443 MG/G CREM DERM CT BG AL X 40 G"
1,ABATACEPTE,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 MG PO LIOF SOL INJ CT 1 FA + SER DESCARTÁVEL
2,ABATACEPTE,505113030019605,1018003900027,7896016807442,-,-,ORENCIA,125 MG/ML SOL INJ SC CT SER PREENCHIDA
3,ABATACEPTE,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 MG/ML SOL INJ SC CT 4 SER PREENC VD TRANS ...
4,ABCIXIMABE,514517110034217,1123634150015,7896212452453,-,-,REOPRO,2 MG/ML SOL INJ CT FA VD INC X 5 ML
...,...,...,...,...,...,...,...,...
29861,ÓXIDO DE MAGNÉSIO;SIMETICONA;HIDRÓXIDO DE ALUM...,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 MG/ML + 60 MG/ML + 7 MG/ML SUS OR CT FR VD...
29862,ÓXIDO DE ZINCO,533507401164427,1039201400023,7898049793914,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CT BG AL X 45G
29863,ÓXIDO DE ZINCO,533507402160425,1039201400031,7898049791309,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CX 50 BG AL X...
29864,ÓXIDO DE ZINCO;RETINOL;COLECALCIFEROL,528526201160419,1256801730019,7898148295500,-,-,PRATIGLÓS,5000 UI/G + 900 UI/G + 150 MG/G POM CX 50 BG A...
29865,ÓXIDO DE ZINCO;ÁCIDO ASCÓRBICO,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 G + 10 MG COM EFERV CT TB PLAS X 10

## Adjust column names

In [3]:
df_cmed = etl.std_cols_names_preprocessing(df_cmed)

In [4]:
df_cmed

,substancia,codigo_ggrem,registro,ean_1,ean_2,ean_3,produto,apresentacao
0,21-ACETATO DE DEXAMETASONA;CLOTRIMAZOL,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,"10 MG/G + 0,443 MG/G CREM DERM CT BG AL X 40 G"
1,ABATACEPTE,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 MG PO LIOF SOL INJ CT 1 FA + SER DESCARTÁVEL
2,ABATACEPTE,505113030019605,1018003900027,7896016807442,-,-,ORENCIA,125 MG/ML SOL INJ SC CT SER PREENCHIDA
3,ABATACEPTE,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 MG/ML SOL INJ SC CT 4 SER PREENC VD TRANS ...
4,ABCIXIMABE,514517110034217,1123634150015,7896212452453,-,-,REOPRO,2 MG/ML SOL INJ CT FA VD INC X 5 ML
...,...,...,...,...,...,...,...,...
29861,ÓXIDO DE MAGNÉSIO;SIMETICONA;HIDRÓXIDO DE ALUM...,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 MG/ML + 60 MG/ML + 7 MG/ML SUS OR CT FR VD...
29862,ÓXIDO DE ZINCO,533507401164427,1039201400023,7898049793914,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CT BG AL X 45G
29863,ÓXIDO DE ZINCO,533507402160425,1039201400031,7898049791309,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CX 50 BG AL X...
29864,ÓXIDO DE ZINCO;RETINOL;COLECALCIFEROL,528526201160419,1256801730019,7898148295500,-,-,PRATIGLÓS,5000 UI/G + 900 UI/G + 150 MG/G POM CX 50 BG A...
29865,ÓXIDO DE ZINCO;ÁCIDO ASCÓRBICO,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 G + 10 MG COM EFERV CT TB PLAS X 10

# Modeling Phase

## Words pre-processing

In [5]:
from tqdm.notebook import tqdm

for idx, row in tqdm(df_cmed.iterrows(), desc = 'CMED words preprocessing',
                     total = df_cmed.shape[0]):
    df_cmed.at[idx, 'substancia'] = etl.std_preprocessing(row['substancia'],
                                                          rem_nums = True,
                                                          rem_stopwords_ai = True,
                                                          correct_ai = True,
                                                          rem_rep_tokens = True)
    
    df_cmed.at[idx, 'apresentacao'] = etl.std_preprocessing(row['apresentacao'],
                                                            rem_stopwords_pr = True)

CMED words preprocessing:   0%|          | 0/29866 [00:00<?, ?it/s]

In [6]:
df_cmed

,substancia,codigo_ggrem,registro,ean_1,ean_2,ean_3,produto,apresentacao
0,dexametasona clotrimazol,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,10 mg g 0 443 mg g crem derm ct bg al x 40 g
1,abatacepte,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 mg po liof sol inj ct 1 fa ser descartavel
2,abatacepte,505113030019605,1018003900027,7896016807442,-,-,ORENCIA,125 mg ml sol inj sc ct ser preenc
3,abatacepte,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 mg ml sol inj sc ct 4 ser preenc vd trans ...
4,abciximabe,514517110034217,1123634150015,7896212452453,-,-,REOPRO,2 mg ml sol inj ct fa vd inc x 5 ml
...,...,...,...,...,...,...,...,...
29861,magnesio simeticona al,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 mg ml 60 mg ml 7 mg ml sus or ct fr vd amb...
29862,zinco,533507401164427,1039201400023,7898049793914,-,-,VITAGLÓS,5500 ui g 990 ui g 150 mg g pom ct bg al x 45 g
29863,zinco,533507402160425,1039201400031,7898049791309,-,-,VITAGLÓS,5500 ui g 990 ui g 150 mg g pom cx 50 bg al x ...
29864,zinco retinol colecalciferol,528526201160419,1256801730019,7898148295500,-,-,PRATIGLÓS,5000 ui g 900 ui g 150 mg g pom cx 50 bg al x ...
29865,zinco ascorbico,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 g 10 mg com eferv ct tb plas x 10

## Clustering CMED items by their Active Ingredients

In [7]:
grouped_cmed = etl.group_cmed(df_cmed, 'substancia', verbose = True)

Grouping active ingredients:   0%|          | 0/2140 [00:00<?, ?it/s]

In [8]:
grouped_cmed

,key,key_sorted,indexes
0,abacavir,abacavir,"[27317, 27318]"
1,abatacepte,abatacepte,"[1, 2, 3]"
2,abciximabe,abciximabe,"[4, 5]"
3,abemaciclibe,abemaciclibe,"[6, 7, 8, 9, 10, 11, 12, 13]"
4,abiraterona,abiraterona,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ..."
...,...,...,...
2067,zoledronico,zoledronico,"[29700, 29701, 29702, 29703, 29704, 29705, 297..."
2068,zolmitriptana,zolmitriptana,"[29378, 29379]"
2069,zolpidem,zolpidem,"[16912, 16913, 16914, 16915, 16916, 16917, 169..."
2070,zopiclona,zopiclona,[29380]
2071,zuclopentixol,zuclopentixol,"[12827, 12828, 29381, 29382]"

## Identifying relevant words

In [9]:
import ir_med

answer_dict = ir_med.identify_relevant_words(df_cmed,
                                             columns=['substancia', 'apresentacao'])

In [10]:
cmed_ai_words = answer_dict['substancia']
cmed_ai_words

array(['abacavir', 'abatacepte', 'abciximabe', ..., 'zopiclona', 'zoster',
       'zuclopentixol'], dtype='<U30')

In [11]:
cmed_pr_words = answer_dict['apresentacao']
cmed_pr_words

array(['0', '00', '000', ..., 'xamp', 'xpe', 'xpect'], dtype='<U16')

# Load the list of medicines extracted from a public notice

In [12]:
df_notice = etl.load_notice('data/notices/1099_2023_25.csv', sep = ',')

In [13]:
df_notice

,item,desc,und,quant,valor_unit,valor_total
0,1,Aciclovir (200mg),Comprimido\n(200mg),145020,0.28,"R$40.605,60"
1,2,Aciclovir 50 mg/g\n(5%),Creme\ndermatológico -\nbisnaga 10 g,24996,3.11,"R$77.737,56"
2,3,Ácido Acetilsalicílico\n100 mg,Comprimido,6000000,0.05,"R$300.000,00"
3,4,Ácido folínico 15 mg,Comprimido,3000,2.09,"R$6.270,00"
4,5,Ácido valpróico 50\nmg/mL,Xarope - frasco 100\nmL,12000,5.45,"R$65.400,00"
...,...,...,...,...,...,...
194,195,Valproato de Sódio\n250 mg,Comprimido,120000,0.52,"R$62.400,00"
195,196,Valproato de Sódio\n500 mg,Comprimido,1200000,1.52,"R$1.824.000,00"
196,197,Valproato de Sódio\n50 mg/ml,Xarope,12000,3.52,"R$42.240,00"
197,198,Varfarina 5 mg,Comprimido,24000,0.13,"R$3.120,00"
198,199,"Verapamil, Cloridrato\n80 mg",Comprimido,60000,1.08,"R$64.800,00"

## Drop unrelevant columns

In [14]:
df_notice.drop(columns = ['item', 'valor_unit', 'valor_total'], inplace = True)

In [15]:
df_notice

,desc,und,quant
0,Aciclovir (200mg),Comprimido\n(200mg),145020
1,Aciclovir 50 mg/g\n(5%),Creme\ndermatológico -\nbisnaga 10 g,24996
2,Ácido Acetilsalicílico\n100 mg,Comprimido,6000000
3,Ácido folínico 15 mg,Comprimido,3000
4,Ácido valpróico 50\nmg/mL,Xarope - frasco 100\nmL,12000
...,...,...,...
194,Valproato de Sódio\n250 mg,Comprimido,120000
195,Valproato de Sódio\n500 mg,Comprimido,1200000
196,Valproato de Sódio\n50 mg/ml,Xarope,12000
197,Varfarina 5 mg,Comprimido,24000
198,"Verapamil, Cloridrato\n80 mg",Comprimido,60000

# Ir-med execution

## Preprocessing of Public Notice Data

In [16]:
import re

# Create copy of original descriptions
df_notice['original_desc'] = df_notice['desc']

# Creation of the column where the indices of the CMED will be stored
df_notice['cmed_indexes'] = ""

# Apply the preprocess function to the columns 'descrição' and 'unidade'
for idx, row in tqdm(df_notice.iterrows(), desc = "Notice words preprocessing",
                     total = df_notice.shape[0]):
    # Remove linebreak in the original description
    df_notice.at[idx, 'original_desc'] = re.sub('\n', '', row['original_desc'])

    df_notice.at[idx, 'desc'] = etl.std_preprocessing(row['desc'],
                                                      correct_ai = True,
                                                      rem_rep_tokens = True)
    
    df_notice.at[idx, 'und'] = etl.std_preprocessing(row['und'],
                                                     rem_stopwords_pr = True)

Notice words preprocessing:   0%|          | 0/199 [00:00<?, ?it/s]

In [17]:
df_notice

,desc,und,quant,original_desc,cmed_indexes
0,aciclovir 200 mg,com 200 mg,145020,Aciclovir (200mg),
1,aciclovir 50 mg g 5,crem derm bg 10 g,24996,Aciclovir 50 mg/g(5%),
2,acido acetilsalicilico 100 mg,com,6000000,Ácido Acetilsalicílico100 mg,
3,acido folico 15 mg,com,3000,Ácido folínico 15 mg,
4,acido valproico 50 mg ml,xpe fr 100 ml,12000,Ácido valpróico 50mg/mL,
...,...,...,...,...,...
194,valproato de sodio 250 mg,com,120000,Valproato de Sódio250 mg,
195,valproato de sodio 500 mg,com,1200000,Valproato de Sódio500 mg,
196,valproato de sodio 50 mg ml,xpe,12000,Valproato de Sódio50 mg/ml,
197,varfarina 5 mg,com,24000,Varfarina 5 mg,
198,verapamil cloridrato 80 mg,com,60000,"Verapamil, Cloridrato80 mg",

## Information Retrival

In [18]:
SAVE_PROCESS_METADATA = True

for idx_X, row_X in tqdm(df_notice.iterrows(), desc= 'IR-Med prediction',
                         total = df_notice.shape[0]):

    desc_ai, desc_pr = ir_med.split_description(row_X['desc'], cmed_ai_words,
                                                cmed_pr_words)

    # Prediction using the IR-Med model
    df_notice.at[idx_X, 'cmed_indexes'], process_metadata = ir_med.predict(df_cmed,
                                                                           grouped_cmed, 
                                                                           desc_ai,
                                                                           desc_pr,
                                                                           row_X['und'])

    if SAVE_PROCESS_METADATA:
        for key, value in process_metadata.items():
            df_notice.at[idx_X, key] = value

IR-Med prediction:   0%|          | 0/199 [00:00<?, ?it/s]

In [19]:
df_notice

,desc,und,quant,original_desc,cmed_indexes,active_ingredient_found,desc_ai,similarity_value,desc_pr,quant_presentations_matched,size_cmed_filtered,pct_set_reduction
0,aciclovir 200 mg,com 200 mg,145020,Aciclovir (200mg),"[532, 533, 535, 537, 540, 542, 544, 547, 549, ...",aciclovir,aciclovir,1.0,200 mg,58.0,133.0,0.563910
1,aciclovir 50 mg g 5,crem derm bg 10 g,24996,Aciclovir 50 mg/g(5%),"[534, 539, 548, 550, 556, 561, 563, 565, 566, ...",aciclovir,aciclovir,1.0,50 mg g 5,32.0,133.0,0.759398
2,acido acetilsalicilico 100 mg,com,6000000,Ácido Acetilsalicílico100 mg,"[665, 666, 667, 668, 669, 670, 671, 672, 29384...",acetilsalicilico,acetilsalicilico,1.0,100 mg,30.0,51.0,0.411765
3,acido folico 15 mg,com,3000,Ácido folínico 15 mg,[29551],folico,folico,1.0,15 mg,1.0,33.0,0.969697
4,acido valproico 50 mg ml,xpe fr 100 ml,12000,Ácido valpróico 50mg/mL,[29691],valproico,valproico,1.0,50 mg ml,1.0,5.0,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...
194,valproato de sodio 250 mg,com,120000,Valproato de Sódio250 mg,"[13411, 13412, 13415, 13418, 13419, 13420, 134...",sodio,sodio,1.0,250 mg,54.0,323.0,0.832817
195,valproato de sodio 500 mg,com,1200000,Valproato de Sódio500 mg,"[13413, 13414, 13416, 13417, 13422, 13423, 134...",sodio,sodio,1.0,500 mg,68.0,323.0,0.789474
196,valproato de sodio 50 mg ml,xpe,12000,Valproato de Sódio50 mg/ml,"[28973, 28974, 28977, 28980, 28981, 28983, 289...",sodio,sodio,1.0,50 mg ml,12.0,323.0,0.962848
197,varfarina 5 mg,com,24000,Varfarina 5 mg,"[29214, 29215, 29216, 29217, 29218, 29219, 292...",varfarina,varfarina,1.0,5 mg,9.0,9.0,0.000000
198,verapamil cloridrato 80 mg,com,60000,"Verapamil, Cloridrato80 mg","[10882, 10883, 10885, 10887, 10889, 10890, 108...",verapamil,verapamil,1.0,80 mg,8.0,11.0,0.272727

# Analysis of the Results

## Predict Active Ingredient Analysis

In [20]:
df_notice['got_ai_right'] = df_notice\
                            .apply(lambda row: ir_med.check_ai_prediction(row['desc'],
                                                                          row['desc_ai'],
                                                                          row['active_ingredient_found']),
                                    axis=1)

In [21]:
GOT_AI_RIGHT = False

df_notice[df_notice['got_ai_right'] == GOT_AI_RIGHT][['got_ai_right', 'desc', 'desc_ai', 'active_ingredient_found']]

,got_ai_right,desc,desc_ai,active_ingredient_found
18,False,amoxicilina clavulonato de potassio 50 mg ml 1...,amoxicilina potassio l,amoxicilina potassio
38,False,carbonato de calcio vitamina d 500 mg 400 ui,calcio vitamina,calcio
107,False,heparina 5 000 ui 0 25 ml,heparina,heparina suina
112,False,hidrogel,,abacavir
157,False,ole mineral,ole,ole soja
175,False,soro glicosado 5,,abacavir
176,False,soro glicosado 5,,abacavir

## Presentations Matched Analysis

In [22]:
df_notice['prs_matched'] = df_notice['cmed_indexes'] \
                           .apply(lambda x: etl.get_presentations(df_cmed, x))

df_notice['common_tokens_prs'] = df_notice['prs_matched']\
                                 .apply(lambda x: ir_med.get_common_tokens(x))

df_notice['got_pr_right'] = df_notice\
                            .apply(lambda row: ir_med.check_pr_predictions(row['desc_pr'],
                                                                           row['und'],
                                                                           row['common_tokens_prs']),
                                    axis=1)

In [25]:
GOT_PR_RIGHT = False

df_notice[df_notice['got_pr_right'] == GOT_AI_RIGHT][['got_pr_right', 'desc',
                                                      'und', 'desc_pr',
                                                      'common_tokens_prs']]

,got_pr_right,desc,und,desc_pr,common_tokens_prs
1,False,aciclovir 50 mg g 5,crem derm bg 10 g,50 mg g 5,"{10, crem, 50, x, g, derm, mg, bg}"
3,False,acido folico 15 mg,com,15 mg,"{0, ml, 5, pebd, 15, x, mg, pead, sus, flac, c..."
4,False,acido valproico 50 mg ml,xpe fr 100 ml,50 mg ml,"{xpe, ml, 5, 250, x, 100, mg, fr, ct, amb, vd}"
6,False,agua para injetaveis,sol inj bg 500 ml,,"{ml, inj, fech, x, 500, sist, sol}"
17,False,amoxicilina clavulonato de potassio 875 mg 125,com,potassio 875 mg 125,"{rev, x, 125, mg, 875, com, ct}"
...,...,...,...,...,...
180,False,sulfametoxazol trimetoprima 40 mg ml 8,sus or fr 100 g,40 mg ml 8,"{ml, 40, x, 100, mg, 8, sus, fr, amb, or}"
184,False,sulfato de magnesio 50 4 05 meq ml mg,sol inj amp 10 ml,50 4 05 meq ml mg,"{10, ml, inj, 50, cx, x, 100, mg, im, vd, iv, ..."
185,False,sulfato de magnesio 10 0 81 meq ml mg,sol inj amp 10 ml,10 0 81 meq ml mg,"{10, ml, inj, cx, x, mg, sol, amp}"
187,False,sulfato de salbutamol 100 mcg dose,aer or fr 200 doses,100 mcg dose,"{x, 100, al, doses, aer, mcg, po, dose, fr, ct..."
193,False,timolol maleato 5 mg ml 0,sol oft fr 5 ml,5 mg ml 0,"{ml, 5, x, mg, got, fr, sol, plas, oft}"

# .csv export

In [24]:
df_X

NameError: name 'df_X' is not defined

In [ ]:
import pandas as pd

index = (pd.Series(right_pr) == True) & (pd.Series(right_apr) == True)
# index = [x if x else "" for x in index]
index = [x for x in index]

In [ ]:
df_X['Hit'] = index

In [ ]:
df_X \
    .drop(columns=['medicamentos'])  \
    [['Hit', 'quant_matched', 'quant_grupo', 'perc_red_conj', 'desc_orig', 'desc', 'string_pr', 'pr_encontrado', 'right_pr', 'und', 'string_apr', 'common_tokens_apr', 'common_tokens_apr_string', 'right_apr']] \
    .to_csv('results/resultados_classificador.csv', sep=';', decimal=',', index=False)