[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ArthurLimaS/ir-med/blob/main/example_notebook.ipynb)

# If on Google Colab

In [2]:
RunningInCOLAB = 'google.colab' in str(get_ipython()) if hasattr(__builtins__,'__IPYTHON__') else False

In [3]:
if RunningInCOLAB:
    from google.colab import output
    output.enable_custom_widget_manager()

    !git clone https://github.com/ArthurLimaS/ir-med.git
    %cd ir-med
    !pip install -r "requirements.txt"

Cloning into 'ir-med'...
remote: Enumerating objects: 304, done.
remote: Counting objects: 100% (304/304), done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 304 (delta 165), reused 235 (delta 115), pack-reused 0 (from 0)
Receiving objects: 100% (304/304), 29.90 MiB | 16.33 MiB/s, done.
Resolving deltas: 100% (165/165), done.
/content/ir-med
Requirement already satisfied: asttokens==3.0.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: camelot-py==1.0.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: cffi==1.17.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (1.17.1)
Requirement already satisfied: chardet==5.2.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: charset-normalizer==3.4.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 5)) (3.4.2)
Requirement already satisfied: click==8.1.8 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 6)) (8.1.8)
Requirement already satisfied: colorama==0.4.6 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: comm==0.2.3 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 8)) (0.2.3)
Requirement already satisfied: cryptography==45.0.5 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 9)) (45.0.5)
Requirement already satisfied: debugpy==1.8.15 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 10)) (1.8.15)
Requirement already satisfied: decorator==5.2.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 11)) (5.2.1)
Requirement already satisfied: et_xmlfile==2.0.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 12)) (2.0.0)
Requirement already satisfied: exceptiongroup==1.3.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 13)) (1.3.0)
Requirement already satisfied: executing==2.2.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 14)) (2.2.0)
Requirement already satisfied: ghostscript==0.8.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 15)) (0.8.1)
Requirement already satisfied: importlib_metadata==8.7.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 16)) (8.7.0)
Requirement already satisfied: ipykernel==6.30.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 17)) (6.30.0)
Requirement already satisfied: ipython==8.18.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 18)) (8.18.1)
Requirement already satisfied: ipywidgets==8.1.7 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 19)) (8.1.7)
Requirement already satisfied: jaro-winkler==2.0.3 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 20)) (2.0.3)
Requirement already satisfied: jedi==0.19.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 21)) (0.19.2)
Requirement already satisfied: joblib==1.5.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 22)) (1.5.1)
Requirement already satisfied: jupyter_client==8.6.3 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 23)) (8.6.3)
Requirement already satisfied: jupyter_core==5.8.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 24)) (5.8.1)
Requirement already satisfied: jupyterlab_widgets==3.0.15 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 25)) (3.0.15)
Requirement already satisfied: matplotlib-inline==0.1.7 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 26)) (0.1.7)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 27)) (1.6.0)
Requirement already satisfied: nltk==3.9.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 28)) (3.9.1)
Requirement already satisfied: numpy==2.0.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 29)) (2.0.2)
Requirement already satisfied: opencv-python-headless==4.12.0.88 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 30)) (4.12.0.88)
Requirement already satisfied: openpyxl==3.1.5 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 31)) (3.1.5)
Requirement already satisfied: packaging==25.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 32)) (25.0)
Requirement already satisfied: pandas==2.3.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 33)) (2.3.1)
Requirement already satisfied: parso==0.8.4 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 34)) (0.8.4)
Requirement already satisfied: pdfminer.six==20250506 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 35)) (20250506)
Requirement already satisfied: pexpect==4.9.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 36)) (4.9.0)
Requirement already satisfied: platformdirs==4.3.8 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 37)) (4.3.8)
Requirement already satisfied: prompt_toolkit==3.0.51 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 38)) (3.0.51)
Requirement already satisfied: psutil==7.0.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 39)) (7.0.0)
Requirement already satisfied: ptyprocess==0.7.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 40)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 41)) (0.2.3)
Requirement already satisfied: pycparser==2.22 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 42)) (2.22)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 43)) (2.19.2)
Requirement already satisfied: pypdf==3.17.4 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 44)) (3.17.4)
Requirement already satisfied: pypdfium2==4.30.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 45)) (4.30.0)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 46)) (2.9.0.post0)
Requirement already satisfied: pytz==2025.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 47)) (2025.2)
Requirement already satisfied: pyzmq==27.0.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 48)) (27.0.0)
Requirement already satisfied: regex==2025.7.34 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 49)) (2025.7.34)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 50)) (1.17.0)
Requirement already satisfied: stack-data==0.6.3 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 51)) (0.6.3)
Requirement already satisfied: tabulate==0.9.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 52)) (0.9.0)
Requirement already satisfied: tornado==6.5.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 53)) (6.5.1)
Requirement already satisfied: tqdm==4.67.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 54)) (4.67.1)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 55)) (5.14.3)
Requirement already satisfied: typing_extensions==4.14.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 56)) (4.14.1)
Requirement already satisfied: tzdata==2025.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 57)) (2025.2)
Requirement already satisfied: Unidecode==1.4.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 58)) (1.4.0)
Requirement already satisfied: wcwidth==0.2.13 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 59)) (0.2.13)
Requirement already satisfied: widgetsnbextension==4.0.14 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 60)) (4.0.14)
Requirement already satisfied: zipp==3.23.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 61)) (3.23.0)

# Loading CMED data

In [4]:
import etl_functions as etl

# Download nltk 'punkt_tab' data [REQUIRED FOR SOME OF THE IR-MED FUNCTIONS]
etl.download_nltk_punkt_tab()

# Load CMED data

df_cmed = etl.load_cmed(path = "data/cmed/cmed_clean_2024_03.csv")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [5]:
df_cmed

,SUBSTÂNCIA,CÓDIGO GGREM,REGISTRO,EAN 1,EAN 2,EAN 3,PRODUTO,APRESENTAÇÃO
0,21-ACETATO DE DEXAMETASONA;CLOTRIMAZOL,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,"10 MG/G + 0,443 MG/G CREM DERM CT BG AL X 40 G"
1,ABATACEPTE,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 MG PO LIOF SOL INJ CT 1 FA + SER DESCARTÁVEL
2,ABATACEPTE,505113030019605,1018003900027,7896016807442,-,-,ORENCIA,125 MG/ML SOL INJ SC CT SER PREENCHIDA
3,ABATACEPTE,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 MG/ML SOL INJ SC CT 4 SER PREENC VD TRANS ...
4,ABCIXIMABE,514517110034217,1123634150015,7896212452453,-,-,REOPRO,2 MG/ML SOL INJ CT FA VD INC X 5 ML
...,...,...,...,...,...,...,...,...
29861,ÓXIDO DE MAGNÉSIO;SIMETICONA;HIDRÓXIDO DE ALUM...,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 MG/ML + 60 MG/ML + 7 MG/ML SUS OR CT FR VD...
29862,ÓXIDO DE ZINCO,533507401164427,1039201400023,7898049793914,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CT BG AL X 45G
29863,ÓXIDO DE ZINCO,533507402160425,1039201400031,7898049791309,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CX 50 BG AL X...
29864,ÓXIDO DE ZINCO;RETINOL;COLECALCIFEROL,528526201160419,1256801730019,7898148295500,-,-,PRATIGLÓS,5000 UI/G + 900 UI/G + 150 MG/G POM CX 50 BG A...
29865,ÓXIDO DE ZINCO;ÁCIDO ASCÓRBICO,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 G + 10 MG COM EFERV CT TB PLAS X 10

### Adjust column names

In [6]:
df_cmed = etl.std_cols_names_preprocessing(df_cmed)

In [7]:
df_cmed

,substancia,codigo_ggrem,registro,ean_1,ean_2,ean_3,produto,apresentacao
0,21-ACETATO DE DEXAMETASONA;CLOTRIMAZOL,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,"10 MG/G + 0,443 MG/G CREM DERM CT BG AL X 40 G"
1,ABATACEPTE,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 MG PO LIOF SOL INJ CT 1 FA + SER DESCARTÁVEL
2,ABATACEPTE,505113030019605,1018003900027,7896016807442,-,-,ORENCIA,125 MG/ML SOL INJ SC CT SER PREENCHIDA
3,ABATACEPTE,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 MG/ML SOL INJ SC CT 4 SER PREENC VD TRANS ...
4,ABCIXIMABE,514517110034217,1123634150015,7896212452453,-,-,REOPRO,2 MG/ML SOL INJ CT FA VD INC X 5 ML
...,...,...,...,...,...,...,...,...
29861,ÓXIDO DE MAGNÉSIO;SIMETICONA;HIDRÓXIDO DE ALUM...,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 MG/ML + 60 MG/ML + 7 MG/ML SUS OR CT FR VD...
29862,ÓXIDO DE ZINCO,533507401164427,1039201400023,7898049793914,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CT BG AL X 45G
29863,ÓXIDO DE ZINCO,533507402160425,1039201400031,7898049791309,-,-,VITAGLÓS,5500UI/G + 990UI/G + 150MG/G POM CX 50 BG AL X...
29864,ÓXIDO DE ZINCO;RETINOL;COLECALCIFEROL,528526201160419,1256801730019,7898148295500,-,-,PRATIGLÓS,5000 UI/G + 900 UI/G + 150 MG/G POM CX 50 BG A...
29865,ÓXIDO DE ZINCO;ÁCIDO ASCÓRBICO,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 G + 10 MG COM EFERV CT TB PLAS X 10

# Modeling Phase

### Words pre-processing

In [8]:
from tqdm.notebook import tqdm

for idx, row in tqdm(df_cmed.iterrows(), desc = 'CMED words preprocessing',
                     total = df_cmed.shape[0]):
    df_cmed.at[idx, 'substancia'] = etl.std_preprocessing(row['substancia'],
                                                          rem_nums = True,
                                                          rem_stopwords_ai = True,
                                                          correct_ai = True,
                                                          rem_rep_tokens = True)

    df_cmed.at[idx, 'apresentacao'] = etl.std_preprocessing(row['apresentacao'],
                                                            rem_stopwords_pr = True)

CMED words preprocessing:   0%|          | 0/29866 [00:00<?, ?it/s]

In [9]:
df_cmed

,substancia,codigo_ggrem,registro,ean_1,ean_2,ean_3,produto,apresentacao
0,dexametasona clotrimazol,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,10 mg g 0 443 mg g crem derm ct bg al x 40 g
1,abatacepte,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 mg po liof sol inj ct 1 fa ser descartavel
2,abatacepte,505113030019605,1018003900027,7896016807442,-,-,ORENCIA,125 mg ml sol inj sc ct ser preenc
3,abatacepte,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 mg ml sol inj sc ct 4 ser preenc vd trans ...
4,abciximabe,514517110034217,1123634150015,7896212452453,-,-,REOPRO,2 mg ml sol inj ct fa vd inc x 5 ml
...,...,...,...,...,...,...,...,...
29861,magnesio simeticona al,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 mg ml 60 mg ml 7 mg ml sus or ct fr vd amb...
29862,zinco,533507401164427,1039201400023,7898049793914,-,-,VITAGLÓS,5500 ui g 990 ui g 150 mg g pom ct bg al x 45 g
29863,zinco,533507402160425,1039201400031,7898049791309,-,-,VITAGLÓS,5500 ui g 990 ui g 150 mg g pom cx 50 bg al x ...
29864,zinco retinol colecalciferol,528526201160419,1256801730019,7898148295500,-,-,PRATIGLÓS,5000 ui g 900 ui g 150 mg g pom cx 50 bg al x ...
29865,zinco ascorbico,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 g 10 mg com eferv ct tb plas x 10

### Clustering CMED items by their Active Ingredients

In [10]:
grouped_cmed = etl.group_cmed(df_cmed, 'substancia', verbose = True)

Grouping active ingredients:   0%|          | 0/2140 [00:00<?, ?it/s]

In [11]:
grouped_cmed

,key,key_sorted,indexes
0,abacavir,abacavir,"[27317, 27318]"
1,abatacepte,abatacepte,"[1, 2, 3]"
2,abciximabe,abciximabe,"[4, 5]"
3,abemaciclibe,abemaciclibe,"[6, 7, 8, 9, 10, 11, 12, 13]"
4,abiraterona,abiraterona,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ..."
...,...,...,...
2067,zoledronico,zoledronico,"[29700, 29701, 29702, 29703, 29704, 29705, 297..."
2068,zolmitriptana,zolmitriptana,"[29378, 29379]"
2069,zolpidem,zolpidem,"[16912, 16913, 16914, 16915, 16916, 16917, 169..."
2070,zopiclona,zopiclona,[29380]
2071,zuclopentixol,zuclopentixol,"[12827, 12828, 29381, 29382]"

### Identifying relevant words

In [12]:
import ir_med

answer_dict = ir_med.identify_relevant_words(df_cmed,
                                             columns=['substancia', 'apresentacao'])

In [13]:
cmed_ai_words = answer_dict['substancia']
cmed_ai_words

array(['abacavir', 'abatacepte', 'abciximabe', ..., 'zopiclona', 'zoster',
       'zuclopentixol'], dtype='<U30')

In [14]:
cmed_pr_words = answer_dict['apresentacao']
cmed_pr_words

array(['0', '00', '000', ..., 'xamp', 'xpe', 'xpect'], dtype='<U16')

# Load the list of medicines extracted from a public notice

In [15]:
df_notice = etl.load_notice('data/notices/csvs/LE_1616_2023_14.csv', sep = ';')

In [16]:
df_notice

,catmat,desc,und,quant,valor_unit,valor_total
0,271689,ÁCIDO \nASCÓRBICO \nconcentração/dosagem \n200...,Frasco 20 mL,198500,"R$ 1,34",265990.00
1,278489,"ÁCIDO FÓLICO concentração/dosagem \n0,2 mg/m...",FRASCO 30 mL,213400,"R$ 4,30",917620.00
2,315056,ÁGUA PARA INJEÇÃO,AMPOLA 10 mL,2311400,"R$ 0,28",647192.00
3,397502,"AGULHA \nHIPODÉRMICA, \nMATERIAL:AÇO \nINOXIDÁ...",CAIXA COM 100 \nUNIDADES,135900,"R$ 9,44",1282896.00
4,269941,"ÁLCOOL \nETÍLICO, \nHIDRATADO, \n70%(70°GL), L...",FRASCO COM \n1000 ML,200654,"R$ 5,39",1081525.06
...,...,...,...,...,...,...
72,292344,SULFATO \nFERROSO \nconcentração/dosagem 40 ...,COMPRIMIDO,6586400,"R$ 0,03",197592.00
73,332468,SULFATO \nFERROSO \nconcentração/dosagem 5 mg/...,FRASCO 100 mL,86420,"R$ 2,68",231605.60
74,272581,TIMOLOL \n– \nMALEATO \nconcentração/dosagem ...,FRASCO 5 mL,23610,"R$ 2,83",66816.30
75,328529,VALPROATO DE SÓDIO \nou ÁCIDO \nVALPRÓICO \...,CÁPSULA OU \nCOMPRIMIDO,2472100,"R$ 0,32",791072.00
76,328532,VALPROATO DE SÓDIO \nou ÁCIDO \nVALPRÓICO ...,FRASCO 100 mL,166750,"R$ 4,06",677005.00

### Drop unrelevant columns

In [17]:
df_notice = df_notice[['desc', 'und']]

In [18]:
df_notice

,desc,und
0,ÁCIDO \nASCÓRBICO \nconcentração/dosagem \n200...,Frasco 20 mL
1,"ÁCIDO FÓLICO concentração/dosagem \n0,2 mg/m...",FRASCO 30 mL
2,ÁGUA PARA INJEÇÃO,AMPOLA 10 mL
3,"AGULHA \nHIPODÉRMICA, \nMATERIAL:AÇO \nINOXIDÁ...",CAIXA COM 100 \nUNIDADES
4,"ÁLCOOL \nETÍLICO, \nHIDRATADO, \n70%(70°GL), L...",FRASCO COM \n1000 ML
...,...,...
72,SULFATO \nFERROSO \nconcentração/dosagem 40 ...,COMPRIMIDO
73,SULFATO \nFERROSO \nconcentração/dosagem 5 mg/...,FRASCO 100 mL
74,TIMOLOL \n– \nMALEATO \nconcentração/dosagem ...,FRASCO 5 mL
75,VALPROATO DE SÓDIO \nou ÁCIDO \nVALPRÓICO \...,CÁPSULA OU \nCOMPRIMIDO
76,VALPROATO DE SÓDIO \nou ÁCIDO \nVALPRÓICO ...,FRASCO 100 mL

# Ir-med execution

### Preprocessing of Public Notice Data

In [19]:
import re

# Create copy of original descriptions
df_notice['original_desc'] = df_notice['desc']

# Creation of the column where the indices of the CMED will be stored
df_notice['cmed_indexes'] = ""

# Apply the preprocess function to the columns 'descrição' and 'unidade'
for idx, row in tqdm(df_notice.iterrows(), desc = "Notice words preprocessing",
                     total = df_notice.shape[0]):
    # Remove linebreak in the original description
    df_notice.at[idx, 'original_desc'] = re.sub('\n', '', row['original_desc'])

    df_notice.at[idx, 'desc'] = etl.std_preprocessing(row['desc'],
                                                      correct_ai = True,
                                                      rem_rep_tokens = True)

    df_notice.at[idx, 'und'] = etl.std_preprocessing(row['und'],
                                                     rem_stopwords_pr = True)

/tmp/ipython-input-1610188768.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_notice['original_desc'] = df_notice['desc']
/tmp/ipython-input-1610188768.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_notice['cmed_indexes'] = ""

Notice words preprocessing:   0%|          | 0/77 [00:00<?, ?it/s]

In [20]:
df_notice

,desc,und,original_desc,cmed_indexes
0,acido ascorbico concentracao dosagem 200 mg ml...,fr 20 ml,ÁCIDO ASCÓRBICO concentração/dosagem 200 mg/mL...,
1,acido folico concentracao dosagem 0 2 mg ml fo...,fr 30 ml,"ÁCIDO FÓLICO concentração/dosagem 0,2 mg/mL,...",
2,agua para injecao,amp 10 ml,ÁGUA PARA INJEÇÃO,
3,agu hipodermica material aco inoxidavel silico...,cx com 100 unidades,"AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SI...",
4,alcool etilico hidratado 70 deggl liq,fr com 1000 ml,"ÁLCOOL ETÍLICO, HIDRATADO, 70%(70°GL), LÍQUIDO",
...,...,...,...,...
72,sulfato ferroso concentracao dosagem 40 mg de ...,com,SULFATO FERROSO concentração/dosagem 40 mg ...,
73,sulfato ferroso concentracao dosagem 5 mg ml f...,fr 100 ml,"SULFATO FERROSO concentração/dosagem 5 mg/mL, ...",
74,timolol maleato concentracao dosagem 5 mg ml f...,fr 5 ml,TIMOLOL – MALEATO concentração/dosagem 5mg/mL...,
75,valproato de sodio ou acido valproico concentr...,cap ou com,VALPROATO DE SÓDIO ou ÁCIDO VALPRÓICO conce...,
76,valproato de sodio ou acido valproico concentr...,fr 100 ml,VALPROATO DE SÓDIO ou ÁCIDO VALPRÓICO conc...,

### Information Retrival

In [21]:
SAVE_PROCESS_METADATA = True

for idx_X, row_X in tqdm(df_notice.iterrows(), desc= 'IR-Med prediction',
                         total = df_notice.shape[0]):

    desc_ai, desc_pr = ir_med.split_description(row_X['desc'], cmed_ai_words,
                                                cmed_pr_words)

    # Prediction using the IR-Med model
    df_notice.at[idx_X, 'cmed_indexes'], process_metadata = ir_med.predict(df_cmed,
                                                                           grouped_cmed,
                                                                           desc_ai,
                                                                           desc_pr,
                                                                           row_X['und'])

    if SAVE_PROCESS_METADATA:
        for key, value in process_metadata.items():
            df_notice.at[idx_X, key] = value

IR-Med prediction:   0%|          | 0/77 [00:00<?, ?it/s]

/tmp/ipython-input-56406694.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_notice.at[idx_X, key] = value

In [22]:
df_notice

,desc,und,original_desc,cmed_indexes,active_ingredient_found,desc_ai,similarity_value,desc_pr,quant_presentations_matched,size_cmed_filtered,pct_set_reduction
0,acido ascorbico concentracao dosagem 200 mg ml...,fr 20 ml,ÁCIDO ASCÓRBICO concentração/dosagem 200 mg/mL...,"[29442, 29444, 29452, 29462, 29468, 29471, 294...",ascorbico,ascorbico,1.000000,200 mg ml sol or got,8.0,63.0,0.873016
1,acido folico concentracao dosagem 0 2 mg ml fo...,fr 30 ml,"ÁCIDO FÓLICO concentração/dosagem 0,2 mg/mL,...","[29550, 29553]",folico,folico,1.000000,0 2 mg ml sol or,2.0,33.0,0.939394
2,agua para injecao,amp 10 ml,ÁGUA PARA INJEÇÃO,"[29752, 29826]",agua injecao,agua injecao,1.000000,injecao,2.0,39.0,0.948718
3,agu hipodermica material aco inoxidavel silico...,cx com 100 unidades,"AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SI...","[1586, 1591, 1596, 1601, 1624, 1628]",apixabana,x,0.703704,agu hipodermica aco 21 g x 1 tipo conector em ...,6.0,94.0,0.936170
4,alcool etilico hidratado 70 deggl liq,fr com 1000 ml,"ÁLCOOL ETÍLICO, HIDRATADO, 70%(70°GL), LÍQUIDO",[29831],alcool polivinilico fenilefrina,alcool,0.838710,alcool 70 liq,1.0,1.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
72,sulfato ferroso concentracao dosagem 40 mg de ...,com,SULFATO FERROSO concentração/dosagem 40 mg ...,"[27751, 27753, 27754, 27757, 27758, 27767, 27768]",ferroso,ferroso ferro ii,0.858929,40 mg ii com or,7.0,23.0,0.695652
73,sulfato ferroso concentracao dosagem 5 mg ml f...,fr 100 ml,"SULFATO FERROSO concentração/dosagem 5 mg/mL, ...","[27744, 27749, 27762, 27763, 27765, 27766]",ferroso,ferroso,1.000000,5 mg ml xpe or,6.0,23.0,0.739130
74,timolol maleato concentracao dosagem 5 mg ml f...,fr 5 ml,TIMOLOL – MALEATO concentração/dosagem 5mg/mL...,"[20365, 20420, 20421, 20422, 20423, 20424, 204...",timolol,timolol,1.000000,5 mg ml,14.0,25.0,0.440000
75,valproato de sodio ou acido valproico concentr...,cap ou com,VALPROATO DE SÓDIO ou ÁCIDO VALPRÓICO conce...,"[29698, 29699]",valproico sodio,sodio valproico,1.000000,ou mg a 250 cap com or,2.0,8.0,0.750000
76,valproato de sodio ou acido valproico concentr...,fr 100 ml,VALPROATO DE SÓDIO ou ÁCIDO VALPRÓICO conc...,[29699],valproico sodio,sodio valproico,1.000000,ou 50 mg ml xpe or,1.0,8.0,0.875000

# Analysis of the Results

### Predict Active Ingredient Analysis

In [23]:
df_notice['got_ai_right'] = df_notice\
                            .apply(lambda row: ir_med.check_ai_prediction(row['desc'],
                                                                          row['desc_ai'],
                                                                          row['active_ingredient_found']),
                                    axis=1)

In [24]:
GOT_AI_RIGHT = False

df_notice[df_notice['got_ai_right'] == GOT_AI_RIGHT][['got_ai_right', 'desc', 'desc_ai', 'active_ingredient_found']]

,got_ai_right,desc,desc_ai,active_ingredient_found
3,False,agu hipodermica material aco inoxidavel silico...,x,apixabana
4,False,alcool etilico hidratado 70 deggl liq,alcool,alcool polivinilico fenilefrina
5,False,alcool etilico hidratado 70 gl gel,alcool,alcool polivinilico fenilefrina
17,False,cateter central aplicacao venoso materia prima...,,abacavir
18,False,cateter periferico aplicacao venoso modelo tip...,,abacavir
19,False,cateter periferico polimero radiopaco venoso a...,,abacavir
32,False,coletor de urina material plas tipo sist abert...,,abacavir
41,False,extrato medicinal principio ativo aquoso de ar...,extrato,extrato seco passiflora
64,False,polimixina b composicao associada com neomicin...,polimixina b neomicina fluocinolona lidocaina,clioquinol prednisolona polimixina b benzocaina
72,False,sulfato ferroso concentracao dosagem 40 mg de ...,ferroso ferro ii,ferroso

### Presentations Matched Analysis

In [25]:
df_notice['prs_matched'] = df_notice['cmed_indexes'] \
                           .apply(lambda x: etl.get_presentations(df_cmed, x))

df_notice['common_tokens_prs'] = df_notice['prs_matched']\
                                 .apply(lambda x: ir_med.get_common_tokens(x))

df_notice['got_pr_right'] = df_notice\
                            .apply(lambda row: ir_med.check_pr_predictions(row['desc_pr'],
                                                                           row['und'],
                                                                           row['common_tokens_prs']),
                                    axis=1)

In [26]:
GOT_PR_RIGHT = False

df_notice[df_notice['got_pr_right'] == GOT_AI_RIGHT][['got_pr_right', 'desc',
                                                      'und', 'desc_pr',
                                                      'common_tokens_prs']]

,got_pr_right,desc,und,desc_pr,common_tokens_prs
2,False,agua para injecao,amp 10 ml,injecao,"{ml, x, cx, amp, 10, sol, inj}"
3,False,agu hipodermica material aco inoxidavel silico...,cx com 100 unidades,agu hipodermica aco 21 g x 1 tipo conector em ...,"{plas, bl, 5, x, pvc, mg, 100, rev, ct, al, co..."
4,False,alcool etilico hidratado 70 deggl liq,fr com 1000 ml,alcool 70 liq,"{ml, 2, oft, plas, x, mg, 1, opc, ct, fr, 15, ..."
5,False,alcool etilico hidratado 70 gl gel,fr com 500 ml,alcool 70 gl gel,"{ml, 2, oft, plas, x, mg, 1, opc, ct, fr, 15, ..."
6,False,alopurinol concentracao dosagem 300 mg forma f...,com,300 mg com or,"{plas, bl, x, mg, ct, al, 300, com, trans}"
7,False,ambroxol cloridrato concentracao dosagem 3 mg ...,fr 100 ml,3 mg ml xpe or,"{3, ml, x, mg, 100, xpe, fr, amb}"
8,False,ambroxol cloridrato concentracao dosagem 6 mg ...,fr 100 ml,6 mg ml xpe or,"{ml, x, mg, 100, xpe, fr, 6}"
9,False,beclometasona dipropionato concentracao dosage...,fr 200 doses,50 mcg dose aer ou spr inal nas,"{sus, plas, x, 200, doses, mcg, ct, fr, valv, ..."
10,False,beclometasona dipropionato concentracao dosage...,fr 200 doses,200 mcg dose po inal or,"{inal, po, 200, x, 100, doses, mcg, ct, dose, ..."
11,False,beclometasona dipropionato concentracao dosage...,fr 200 doses,250 mcg dose aer ou spr inal nas,"{aer, x, 200, doses, mcg, ct, al, tb, sol, dos..."
12,False,biperideno cloridrato concentracao dosagem 2 m...,com,2 mg com or,"{2, bl, x, plas, mg, al, com}"
14,False,budesonida concentracao dosagem 50 mcg forma f...,fr 120 doses,50 mcg aer nas inal,"{ml, sus, plas, x, aquosa, 120, doses, opc, mc..."
15,False,captopril concentracao dosagem 25 mg forma far...,com,25 mg com or,"{x, mg, 25, al, com}"
16,False,carbamazepina concentracao dosagem 200 mg form...,com,200 mg com or,"{com, x, 200, mg}"
17,False,cateter central aplicacao venoso materia prima...,unidade,7 fr duplo 14 a 18 20 cm tipo sc conector em comp,"{ml, plas, x, mg, 240, 20, opc, ct, fr, or, sol}"
18,False,cateter periferico aplicacao venoso modelo tip...,unidade,tipo escalpe agu aco inox 21 c tb extensor con...,"{plas, x, mg, opc, ct}"
19,False,cateter periferico polimero radiopaco venoso a...,unidade,agu aco inox 22 25 mm conector cam c filtro si...,"{plas, x, mg, opc, ct}"
20,False,cetoconazol concentracao dosagem 2 20 mg g for...,fr 100 ml,2 20 mg g xamp,"{ml, plas, x, mg, 100, 20, opc, ct, fr, xamp, g}"
21,False,cetoprofeno concentracao dosagem 100 mg forma ...,fr amp,100 mg po sol inj,"{fa, po, mg, 100, ct, iv, 50, infus, vd, amb, ..."
23,False,ciprofloxacino cloridrato concentracao dosagem...,com,500 mg com or,"{x, mg, rev, 500, ct, al, com}"
24,False,clomipramina cloridrato concentracao dosagem 1...,com,10 mg com or,"{plas, bl, x, pvc, mg, rev, opc, 10, ct, al, c..."
26,False,clonidina cloridrato concentracao 0 1 mg,com,0 1 mg,"{plas, bl, x, mg, 30, ct, al, com, 0}"
27,False,cloreto de sodio 0 9 sol inj 100 ml sist fech,bols ou fr 100 ml,0 9 sol inj 100 ml sist fech,"{ml, sist, x, 9, 100, iv, fech, sol, inj}"
29,False,clorpromazina cloridrato concentracao dosagem ...,com,100 mg com or,"{plas, bl, x, mg, 100, rev, al, com}"
30,False,colagenase associada com cloranfenicol concent...,bg 30 g,com 0 6 ui 1 01 g pom,"{x, 30, pom, bg, ct, al, 6, 0, g}"
31,False,colagenase concentracao dosagem 0 6 ui forma f...,bg 30 g,0 6 ui pom,"{x, 30, pom, bg, al, derm, u, 6, 0, g}"
32,False,coletor de urina material plas tipo sist abert...,unidade,plas tipo sist 1200 ml esteril descartavel,"{ml, plas, x, mg, 240, 20, opc, ct, fr, or, sol}"
34,False,digoxina concentracao dosagem 0 25 mg forma fa...,com,0 25 mg com or,"{plas, bl, x, mg, 25, al, com, 0}"
36,False,enalapril maleato concentracao dosagem 20 mg f...,com,20 mg com or,"{com, 20, x, mg}"
38,False,eritromicina estolato concentracao dosagem 500...,com,500 mg com or,"{plas, bl, x, com, mg, ct, al, 500}"
39,False,estrogenios conjugados concentracao dosagem 0 ...,bg 25 g,0 625 mg g crem vag,"{plas, bl, x, mg, ct, 625, al, 28, 0, trans}"
40,False,estrogenios conjugados concentracao dosagem 0 ...,com ou dragea,0 3 mg com or,"{3, plas, bl, x, mg, ct, al, drg, 28, env, 0, ..."
41,False,extrato medicinal principio ativo aquoso de ar...,bg 60 g,gel vag com,"{plas, ct, x, mg}"
44,False,fenobarbital concentracao dosagem 100 mg forma...,com,100 mg com or,"{plas, bl, x, mg, 100, al, com}"
46,False,fluoxetina cloridrato concentracao dosagem 20 ...,cap ou com,20 mg cap ou com or,"{plas, bl, x, mg, 20, al, dura, cap}"
47,False,furosemida concentracao dosagem 40 mg forma fa...,com,40 mg com or,"{plas, bl, x, mg, 40, al, com}"
49,False,glibenclamida concentracao dosagem 5 mg forma ...,com,5 mg com or,"{plas, bl, 5, x, mg, al, com}"
50,False,gliclazida concentracao dosagem 80 mg forma fa...,com,80 mg com or,"{prol, bl, x, mg, al, com, lib}"
51,False,glicose concentracao 5 indicacao sol inj carac...,bols 500 00 ml,glicose 5 sol inj sist fech,"{ml, sist, x, mg, iv, fech, sol, 500, inj, bols}"
53,False,haloperidol concentracao dosagem 5 mg forma fa...,com,5 mg com or,"{plas, bl, 5, x, mg, al, com, trans}"
56,False,ivermectina concentracao dosagem 6 mg forma fa...,com,6 mg com or,"{x, mg, ct, al, com, 6}"
57,False,loratadina concentracao dosagem 10 mg forma fa...,com,10 mg com or,"{plas, bl, x, mg, 10, al, com}"
58,False,metformina cloridrato concentracao dosagem 850...,com,850 mg com or,"{bl, x, mg, al, 850, com}"
60,False,metronidazol concentracao dosagem 100 mg g for...,bg 50 g,100 mg g gel vag com aplic,"{x, vag, aplic, mg, 100, bg, al, 50, gel, g}"
62,False,noretisterona concentracao dosagem 0 35 mg for...,bl,0 35 mg bl or,"{plas, bl, x, mg, 35, ct, al, com, 0, trans}"
63,False,omeprazol concentracao dosagem 20 mg forma far...,cap,20 mg cap or,"{x, mg, 20, ct, dura, cap}"
64,False,polimixina b composicao associada com neomicin...,fr 5 00 ml,b com 11 000 ui 3 85 mg 0 275 20 ml uso sol oto,"{5, x, mg, 000, 30, g, pom, ui, 10, bg, ct, al..."
66,False,retinol composicao associado c aminoacidos met...,bg 3 50 g,c 10 000 ui 25 mg 5 g pom oft,"{3, oft, 5, x, 000, mg, pom, ui, 10, bg, 25, c..."
68,False,simeticona concentracao dosagem 75 mg ml forma...,fr 15 ml,75 mg ml sol or got,"{ml, plas, x, mg, 75, opc, ct, fr, 15, got, or}"
69,False,sinvastatina concentracao dosagem 10 mg forma ...,com,10 mg com or,"{bl, x, mg, rev, 10, ct, al, com}"
70,False,sinvastatina concentracao dosagem 40 mg forma ...,com,40 mg com or,"{bl, x, mg, rev, 40, al, com}"
72,False,sulfato ferroso concentracao dosagem 40 mg de ...,com,40 mg ii com or,"{plas, bl, x, mg, rev, 40, ct, al, com}"
73,False,sulfato ferroso concentracao dosagem 5 mg ml f...,fr 100 ml,5 mg ml xpe or,"{ml, x, mg, 100, xpe, fr, amb}"
75,False,valproato de sodio ou acido valproico concentr...,cap ou com,ou mg a 250 cap com or,"{x, mg, 250, ct, fr, mole, cap, vd, amb}"
76,False,valproato de sodio ou acido valproico concentr...,fr 100 ml,ou 50 mg ml xpe or,"{x, mg, ct, fr, mole, 50, cap, vd, 250, amb}"

# .csv export

In [27]:
df_notice

,desc,und,original_desc,cmed_indexes,active_ingredient_found,desc_ai,similarity_value,desc_pr,quant_presentations_matched,size_cmed_filtered,pct_set_reduction,got_ai_right,prs_matched,common_tokens_prs,got_pr_right
0,acido ascorbico concentracao dosagem 200 mg ml...,fr 20 ml,ÁCIDO ASCÓRBICO concentração/dosagem 200 mg/mL...,"[29442, 29444, 29452, 29462, 29468, 29471, 294...",ascorbico,ascorbico,1.000000,200 mg ml sol or got,8.0,63.0,0.873016,True,"[200 mg ml sol or ct fr plas got x 20 ml, 200 ...","{ml, x, 200, mg, 20, fr, got, or, sol}",True
1,acido folico concentracao dosagem 0 2 mg ml fo...,fr 30 ml,"ÁCIDO FÓLICO concentração/dosagem 0,2 mg/mL,...","[29550, 29553]",folico,folico,1.000000,0 2 mg ml sol or,2.0,33.0,0.939394,True,"[0 2 mg ml sol or ct fr got plas amb x 30 ml, ...","{ml, 2, plas, x, mg, 30, fr, or, sol, amb, 0}",True
2,agua para injecao,amp 10 ml,ÁGUA PARA INJEÇÃO,"[29752, 29826]",agua injecao,agua injecao,1.000000,injecao,2.0,39.0,0.948718,True,"[sol inj cx 100 amp poliet x 10 ml, sol inj cx...","{ml, x, cx, amp, 10, sol, inj}",False
3,agu hipodermica material aco inoxidavel silico...,cx com 100 unidades,"AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SI...","[1586, 1591, 1596, 1601, 1624, 1628]",apixabana,x,0.703704,agu hipodermica aco 21 g x 1 tipo conector em ...,6.0,94.0,0.936170,False,[2 5 mg com rev ct bl al plas pvc pvdc trans x...,"{plas, bl, 5, x, pvc, mg, 100, rev, ct, al, co...",False
4,alcool etilico hidratado 70 deggl liq,fr com 1000 ml,"ÁLCOOL ETÍLICO, HIDRATADO, 70%(70°GL), LÍQUIDO",[29831],alcool polivinilico fenilefrina,alcool,0.838710,alcool 70 liq,1.0,1.0,0.000000,False,[1 2 mg ml 14 0 mg ml sol oft ct fr plas opc g...,"{ml, 2, oft, plas, x, mg, 1, opc, ct, fr, 15, ...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,sulfato ferroso concentracao dosagem 40 mg de ...,com,SULFATO FERROSO concentração/dosagem 40 mg ...,"[27751, 27753, 27754, 27757, 27758, 27767, 27768]",ferroso,ferroso ferro ii,0.858929,40 mg ii com or,7.0,23.0,0.695652,False,"[40 mg com rev ct bl al plas pvc trans x 50, 4...","{plas, bl, x, mg, rev, 40, ct, al, com}",False
73,sulfato ferroso concentracao dosagem 5 mg ml f...,fr 100 ml,"SULFATO FERROSO concentração/dosagem 5 mg/mL, ...","[27744, 27749, 27762, 27763, 27765, 27766]",ferroso,ferroso,1.000000,5 mg ml xpe or,6.0,23.0,0.739130,True,"[10 mg ml xpe ct fr vd amb x 100 ml, 25 mg ml ...","{ml, x, mg, 100, xpe, fr, amb}",False
74,timolol maleato concentracao dosagem 5 mg ml f...,fr 5 ml,TIMOLOL – MALEATO concentração/dosagem 5mg/mL...,"[20365, 20420, 20421, 20422, 20423, 20424, 204...",timolol,timolol,1.000000,5 mg ml,14.0,25.0,0.440000,True,"[2 5 mg ml sol oft ct fr got plas opc x 5 ml, ...","{ml, plas, oft, 5, x, mg, fr, got}",True
75,valproato de sodio ou acido valproico concentr...,cap ou com,VALPROATO DE SÓDIO ou ÁCIDO VALPRÓICO conce...,"[29698, 29699]",valproico sodio,sodio valproico,1.000000,ou mg a 250 cap com or,2.0,8.0,0.750000,True,"[250 mg cap mole ct fr vd amb x 25, 250 mg cap...","{x, mg, 250, ct, fr, mole, cap, vd, amb}",False
76,valproato de sodio ou acido valproico concentr...,fr 100 ml,VALPROATO DE SÓDIO ou ÁCIDO VALPRÓICO conc...,[29699],valproico sodio,sodio valproico,1.000000,ou 50 mg ml xpe or,1.0,8.0,0.875000,True,[250 mg cap mole ct fr vd amb x 50],"{x, mg, ct, fr, mole, 50, cap, vd, 250, amb}",False

In [28]:
df_notice.to_csv('algorithm_results.csv',
                 sep=';', decimal=',', index=False)